<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net40</TargetFramework>
    <AssemblyName>Microsoft.Xna.Framework.Content.Pipeline</AssemblyName>
    <RootNamespace>Microsoft.Xna.Framework.Content.Pipeline</RootNamespace>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <FileVersion>4.0.0.0</FileVersion>
    <Deterministic>true</Deterministic>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <SignAssembly Condition="'$(XnaPublicKeyFile)' != ''">true</SignAssembly>
    <DelaySign Condition="'$(XnaPublicKeyFile)' != ''">true</DelaySign>
    <AssemblyOriginatorKeyFile Condition="'$(XnaPublicKeyFile)' != ''">$(XnaPublicKeyFile)</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net40" Version="1.0.3" PrivateAssets="all" />
    <Reference Include="Microsoft.Xna.Framework.Graphics">
      <HintPath>$(XnaReferenceDirectory)\Microsoft.Xna.Framework.Graphics.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
